openapi: 3.0.0
info:
  title: For Discount
  description: An api to access your Routes
  version: 1.0.0
servers: 
  - url: http://localhost:8030
  
paths:
  /updateUserCoupon/{userId}:
    put:
      summary: discount .
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coupon:
                  type : string
                discount:
                  type : number
                
      responses:
        "200":
          description: coupon updated
          
  /useUserCoupon/{userId}:
    put:
      summary: discount .
      parameters:
        - in: path
          name: userId
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coupon:
                  type : string
                discount:
                  type : number
                
      responses:
        "200":
          description: coupon updated